/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsAarRouteImport } from './routes/projects.aar'
import { Route as ProjectsRadiaxRouteImport } from './routes/projects.radiax'
import { Route as ProjectsSwachRouteImport } from './routes/projects.swach'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsAarRoute = ProjectsAarRouteImport.update({
  id: '/projects/aar',
  path: '/projects/aar',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRadiaxRoute = ProjectsRadiaxRouteImport.update({
  id: '/projects/radiax',
  path: '/projects/radiax',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSwachRoute = ProjectsSwachRouteImport.update({
  id: '/projects/swach',
  path: '/projects/swach',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects/aar': typeof ProjectsAarRoute
  '/projects/radiax': typeof ProjectsRadiaxRoute
  '/projects/swach': typeof ProjectsSwachRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projects/aar': typeof ProjectsAarRoute
  '/projects/radiax': typeof ProjectsRadiaxRoute
  '/projects/swach': typeof ProjectsSwachRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projects/aar': typeof ProjectsAarRoute
  '/projects/radiax': typeof ProjectsRadiaxRoute
  '/projects/swach': typeof ProjectsSwachRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/projects/aar' | '/projects/radiax' | '/projects/swach'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/projects/aar' | '/projects/radiax' | '/projects/swach'
  id:
    '__root__' | '/' | '/projects/aar' | '/projects/radiax' | '/projects/swach'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectsAarRoute: typeof ProjectsAarRoute
  ProjectsRadiaxRoute: typeof ProjectsRadiaxRoute
  ProjectsSwachRoute: typeof ProjectsSwachRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/aar': {
      id: '/projects/aar'
      path: '/projects/aar'
      fullPath: '/projects/aar'
      preLoaderRoute: typeof ProjectsAarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/radiax': {
      id: '/projects/radiax'
      path: '/projects/radiax'
      fullPath: '/projects/radiax'
      preLoaderRoute: typeof ProjectsRadiaxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/swach': {
      id: '/projects/swach'
      path: '/projects/swach'
      fullPath: '/projects/swach'
      preLoaderRoute: typeof ProjectsSwachRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectsAarRoute: ProjectsAarRoute,
  ProjectsRadiaxRoute: ProjectsRadiaxRoute,
  ProjectsSwachRoute: ProjectsSwachRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
